version: '3.9'

services:
  schedule_db:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: schedule
    ports:
      - '5432:5432'
    volumes:
      - schedule_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    volumes:
      - schedule_pgadmin:/var/lib/postgresql/data
    depends_on:
      - schedule_db

volumes:
  schedule_data:
  schedule_pgadmin:
